exclude:
  - README.md
  - .gitignore
  - source_assets
  - config.rb
permalink: news/:year/:month/:day/:title
baseurl: 

domain: http://www.globalresiliencepartnership.org

collections:
  index_sections:
    output: false
  careers:
    output: true
  our_team:
    output: true 
  events:
    output: false    
  selected_teams:
    output: true
    permalink: /teams/:path/
