exclude:
  - README.md
  - .gitignore
  - source_assets
  - config.rb
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: blog/:year/:month/:day/:title
baseurl: 

domain: http://www.globalresiliencepartnership.org

collections:
  index_sections:
    output: false

  selected_teams:
    output: false

prose:
  rooturl: _posts
  site: http://www.globalresiliencepartnership.org
  media: resource
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          value: "title"
      - name: "subtitle"
        field:
          element: "text"
          value: "subtitle"
