exclude:
  - README.md
  - .gitignore
  - source_assets
  - config.rb
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: blog/:title
baseurl: 

collections:
  index_sections:
    output: false

  selected_teams:
    output: false
