exclude:
  - README.md
  - .gitignore
  - source_assets
  - config.rb
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: blog/:year/:month/:day/:title
baseurl: /rockefeller-grp

collections:
  index_sections:
    output: false

  events:
    output: false    
  selected_teams:
    output: true
    permalink: /teams/:path/
