exclude:
  - README.md
  - .gitignore
  - source_assets
  - config.rb
permalink: news/:year/:month/:day/:title
baseurl: /grp
domain: 
collections:
  index_sections:
    output: false

  events:
    output: false    
  selected_teams:
    output: true
    permalink: /teams/:path/
